In [4]:
import pandas as pd

df = pd.read_csv('Final_data.csv')
display(df.info())
display(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 54 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             20000 non-null  float64
 1   Gender                          20000 non-null  object
 2   Weight (kg)                     20000 non-null  float64
 3   Height (m)                      20000 non-null  float64
 4   Max_BPM                         20000 non-null  float64
 5   Avg_BPM                         20000 non-null  float64
 6   Resting_BPM                     20000 non-null  float64
 7   Session_Duration (hours)        20000 non-null  float64
 8   Calories_Burned                 20000 non-null  float64
 9   Workout_Type                    20000 non-null  object
 10  Fat_Percentage                  20000 non-null  float64
 11  Water_Intake (liters)           20000 non-null  float64
 12  Workout_Frequency (days/week)   20000 non-null  float64
 13  Experience_Level                20000 non-null  float64
 14  BMI                             20000 non-null  float64
 15  Daily meals frequency           20000 non-null  float64
 16  Physical exercise               20000 non-null  float64
 17  Carbs                           20000 non-null  float64
 18  Proteins                        20000 non-null  float64
 19  Fats                            20000 non-null  float64
 20  Calories                        20000 non-null  float64
 21  meal_name                       20000 non-null  object
 22  meal_type                       20000 non-null  object
 23  diet_type                       20000 non-null  object
 24  sugar_g                         20000 non-null  float64
 25  sodium_mg                       20000 non-null  float64
 26  cholesterol_mg                  20000 non-null  float64
 27  serving_size_g                  20000 non-null  float64
 28  cooking_method                  20000 non-null  object
 29  prep_time_min                   20000 non-null  float64
 30  cook_time_min                   20000 non-null  float64
 31  rating                          20000 non-null  float64
 32  Name of Exercise                20000 non-null  object
 33  Sets                            20000 non-null  float64
 34  Reps                            20000 non-null  float64
 35  Benefit                         20000 non-null  object
 36  Burns Calories (per 30 min)     20000 non-null  float64
 37  Target Muscle Group             20000 non-null  object
 38  Equipment Needed                20000 non-null  object
 39  Difficulty Level                20000 non-null  object
 40  Body Part                       20000 non-null  object
 41  Type of Muscle                  20000 non-null  object
 42  Workout                         20000 non-null  object
 43  BMI_calc                        20000 non-null  float64
 44  cal_from_macros                 20000 non-null  float64
 45  pct_carbs                       20000 non-null  float64
 46  protein_per_kg                  20000 non-null  float64
 47  pct_HRR                         20000 non-null  float64
 48  pct_maxHR                       20000 non-null  float64
 49  cal_balance                     20000 non-null  float64
 50  lean_mass_kg                    20000 non-null  float64
 51  expected_burn                   20000 non-null  float64
 52  Burns Calories (per 30 min)_bc  20000 non-null  float64
 53  Burns_Calories_Bin              20000 non-null  object
dtypes: float64(39), object(15)
memory usage: 8.2+ MB

None

,Age,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Fat_Percentage,Water_Intake (liters),...,BMI_calc,cal_from_macros,pct_carbs,protein_per_kg,pct_HRR,pct_maxHR,cal_balance,lean_mass_kg,expected_burn,Burns Calories (per 30 min)_bc
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04
mean,38.851454,73.898832,1.723094,179.889702,143.704306,62.195813,1.259446,1280.109601,26.101313,2.627486,...,24.921651,1998.297076,0.499983,1.460142,0.699005,0.802305,744.308699,53.786384,866.352318,8.631802e+19
std,12.114580,21.173010,0.127033,11.510805,14.267688,7.289351,0.341336,502.228982,4.996160,0.604724,...,6.701144,440.848408,0.001455,0.518946,0.144880,0.096613,720.946619,12.498740,250.317069,3.197579e+19
min,18.000000,39.180000,1.490000,159.310000,119.070000,49.490000,0.490000,323.110000,11.333134,1.460000,...,12.037907,1105.570000,0.492434,0.516706,0.371344,0.599789,-1266.220000,30.946261,219.852800,2.491905e+16
25%,28.170000,58.160000,1.620000,170.057500,131.220000,55.960000,1.050000,910.800000,22.387807,2.170000,...,20.094975,1661.022500,0.499054,1.076294,0.583656,0.727676,261.432500,44.587037,714.098250,6.441978e+19
50%,39.865000,70.000000,1.710000,180.140000,142.990000,62.200000,1.270000,1231.450000,25.822504,2.610000,...,24.119097,1943.130000,0.499981,1.382260,0.686284,0.794834,691.190000,51.204908,868.721400,8.371578e+19
75%,49.630000,86.100000,1.800000,189.425000,156.060000,68.090000,1.460000,1553.112500,29.676026,3.120000,...,28.562620,2271.950000,0.500910,1.750495,0.798196,0.869211,1176.290000,61.939016,1012.532700,1.100442e+20
max,59.670000,130.770000,2.010000,199.640000,169.840000,74.500000,2.020000,2890.820000,35.000000,3.730000,...,50.229544,3699.540000,0.507889,3.916881,1.073939,1.047032,3075.580000,90.117371,1477.108800,1.756614e+20

In [5]:
corr = df.corr(numeric_only=True)['Calories_Burned'].sort_values(ascending=False)
print(corr)

Calories_Burned                   1.000000
Session_Duration (hours)          0.814368
expected_burn                     0.773932
Experience_Level                  0.697116
Workout_Frequency (days/week)     0.582787
Water_Intake (liters)             0.262731
cholesterol_mg                    0.072296
Physical exercise                 0.049113
Calories                          0.047981
Reps                              0.043237
serving_size_g                    0.029458
Daily meals frequency             0.028158
rating                            0.025625
Sets                              0.024164
lean_mass_kg                      0.023134
Carbs                             0.011929
cal_from_macros                   0.011817
Fats                              0.011769
Proteins                          0.011602
pct_HRR                           0.010506
pct_carbs                         0.009419
Height (m)                        0.009211
Avg_BPM                           0.007984
Burns Calories (per 30 min)       0.006562
pct_maxHR                         0.006106
Max_BPM                           0.003136
Resting_BPM                      -0.001633
Weight (kg)                      -0.001994
prep_time_min                    -0.002823
sugar_g                          -0.003044
BMI                              -0.004494
BMI_calc                         -0.004495
sodium_mg                        -0.009472
Burns Calories (per 30 min)_bc   -0.013504
Age                              -0.021396
Fat_Percentage                   -0.033812
protein_per_kg                   -0.035982
cook_time_min                    -0.061617
cal_balance                      -0.660560
Name: Calories_Burned, dtype: float64

In [8]:
df = df.drop(columns=[col for col in df.columns if col not in ['Session_Duration (hours)', 'Experience_Level', 'Water_Intake (liters)', 'Calories_Burned']])
display(df.info())
display(df.describe())

df.to_csv('Calories_Burned.csv', index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Session_Duration (hours)  20000 non-null  float64
 1   Calories_Burned           20000 non-null  float64
 2   Water_Intake (liters)     20000 non-null  float64
 3   Experience_Level          20000 non-null  float64
dtypes: float64(4)
memory usage: 625.1 KB

None

,Session_Duration (hours),Calories_Burned,Water_Intake (liters),Experience_Level
count,20000.000000,20000.000000,20000.000000,20000.000000
mean,1.259446,1280.109601,2.627486,1.809176
std,0.341336,502.228982,0.604724,0.736204
min,0.490000,323.110000,1.460000,1.000000
25%,1.050000,910.800000,2.170000,1.010000
50%,1.270000,1231.450000,2.610000,1.990000
75%,1.460000,1553.112500,3.120000,2.020000
max,2.020000,2890.820000,3.730000,3.050000